config/routes.rb
Rails.application.routes.draw do

  resources :goal_data_pts
  resources :skills
  resources :goals
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static#index'

end

app/models/goal_data_pt.rb
class GoalDataPt < ActiveRecord::Base
  belongs_to :goal

  after_create :reminder

  # Notify our appointment attendee X minutes before the appointment time
  def reminder
    @twilio_number = ENV['TWILIO_NUMBER']
    @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    
    # get necessary details to schedule reminder from goal and user
    @goal = Goal.where("id = #{self.goal_id}").first
    minutes = @goal.time_allotted
    data_pts = @goal.total_data_pts

    @user = User.where("id = #{@goal.user_id}").first
    phone_number = @user.phone_number.floor
    goal_title = @goal.goal_title
    # call a function to automate the series of texts to run 

    reminder = "This is your reminder for goal: #{goal_title}"
    message = @client.account.messages.create(
      :from => @twilio_number,
      :to => phone_number,
      :body => reminder,
    )
    puts message.to
  end

	def when_to_run
		  # get self.goal info
		  goal = Goal.where("id = #{self.goal_id}").first
		  minutes = goal.time_allotted
		  data_pts = goal.total_data_pts
		  minute_interval = minutes/data_pts

		  interval_num = self.data_pt_num

			Time.now + minute_interval*(interval_num+1).minutes
			
	end

  handle_asynchronously :reminder, :run_at => Proc.new { |i| i.when_to_run }
end

app/controllers/goal_data_pts_controller.rb
class GoalDataPtsController < ApplicationController
  before_action :set_goal_data_pt, only: [:show, :edit, :update, :destroy]

  # GET /goal_data_pts
  # GET /goal_data_pts.json
  def index
    @goal_data_pts = GoalDataPt.all
  end

  # GET /goal_data_pts/1
  # GET /goal_data_pts/1.json
  def show
  end

  # GET /goal_data_pts/new
  def new
    @goal_data_pt = GoalDataPt.new
  end

  # GET /goal_data_pts/1/edit
  def edit
  end

  # POST /goal_data_pts
  # POST /goal_data_pts.json
  def create
    @goal_data_pt = GoalDataPt.new(goal_data_pt_params)

    respond_to do |format|
      if @goal_data_pt.save
        format.html { redirect_to @goal_data_pt, notice: 'Goal data pt was successfully created.' }
        format.json { render :show, status: :created, location: @goal_data_pt }
      else
        format.html { render :new }
        format.json { render json: @goal_data_pt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goal_data_pts/1
  # PATCH/PUT /goal_data_pts/1.json
  def update
    respond_to do |format|
      if @goal_data_pt.update(goal_data_pt_params)
        format.html { redirect_to @goal_data_pt, notice: 'Goal data pt was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal_data_pt }
      else
        format.html { render :edit }
        format.json { render json: @goal_data_pt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goal_data_pts/1
  # DELETE /goal_data_pts/1.json
  def destroy
    @goal_data_pt.destroy
    respond_to do |format|
      format.html { redirect_to goal_data_pts_url, notice: 'Goal data pt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_data_pt
      @goal_data_pt = GoalDataPt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_data_pt_params
      params.require(:goal_data_pt).permit(:data_pt_num, :perceived_performance, :perceived_progress, :actual_progress, :goal_id)
    end
end

app/helpers/goal_data_pts_helper.rb
module GoalDataPtsHelper
end

app/views/goal_data_pts/_form.html.erb
<%= form_for(@goal_data_pt) do |f| %>
  <% if @goal_data_pt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal_data_pt.errors.count, "error") %> prohibited this goal_data_pt from being saved:</h2>

      <ul>
      <% @goal_data_pt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_pt_num %><br>
    <%= f.number_field :data_pt_num %>
  </div>
  <div class="field">
    <%= f.label :perceived_performance %><br>
    <%= f.number_field :perceived_performance %>
  </div>
  <div class="field">
    <%= f.label :perceived_progress %><br>
    <%= f.text_field :perceived_progress %>
  </div>
  <div class="field">
    <%= f.label :actual_progress %><br>
    <%= f.text_field :actual_progress %>
  </div>
  <div class="field">
    <%= f.label :goal_id %><br>
    <%= f.text_field :goal_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goal_data_pts/edit.html.erb
<h1>Editing Goal Data Pt</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal_data_pt %> |
<%= link_to 'Back', goal_data_pts_path %>

app/views/goal_data_pts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Goal Data Pts</h1>

<table>
  <thead>
    <tr>
      <th>Data pt num</th>
      <th>Perceived performance</th>
      <th>Perceived progress</th>
      <th>Actual progress</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goal_data_pts.each do |goal_data_pt| %>
      <tr>
        <td><%= goal_data_pt.data_pt_num %></td>
        <td><%= goal_data_pt.perceived_performance %></td>
        <td><%= goal_data_pt.perceived_progress %></td>
        <td><%= goal_data_pt.actual_progress %></td>
        <td><%= goal_data_pt.goal %></td>
        <td><%= link_to 'Show', goal_data_pt %></td>
        <td><%= link_to 'Edit', edit_goal_data_pt_path(goal_data_pt) %></td>
        <td><%= link_to 'Destroy', goal_data_pt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal data pt', new_goal_data_pt_path %>

app/views/goal_data_pts/new.html.erb
<h1>New Goal Data Pt</h1>

<%= render 'form' %>

<%= link_to 'Back', goal_data_pts_path %>

app/views/goal_data_pts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data pt num:</strong>
  <%= @goal_data_pt.data_pt_num %>
</p>

<p>
  <strong>Perceived performance:</strong>
  <%= @goal_data_pt.perceived_performance %>
</p>

<p>
  <strong>Perceived progress:</strong>
  <%= @goal_data_pt.perceived_progress %>
</p>

<p>
  <strong>Actual progress:</strong>
  <%= @goal_data_pt.actual_progress %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @goal_data_pt.goal %>
</p>

<%= link_to 'Edit', edit_goal_data_pt_path(@goal_data_pt) %> |
<%= link_to 'Back', goal_data_pts_path %>