config/routes.rb
Rails.application.routes.draw do

  resources :goal_data_pts
  resources :skills
  resources :goals
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :goal_data_pts
end

app/controllers/goals_controller.rb
require 'twilio-ruby'

class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

      if @goal.save
      # prepare translation into minutes 
        time_allotted_units = params[:time_allotted_units]
        time_allotted = params[:goal][:time_allotted]
        goal_id = @goal.id
        calculate_minutes_texts(time_allotted, time_allotted_units, goal_id)
      # prepare Twilio data for sending initial text
        goal_title = @goal.goal_title
        goal_user_id = @goal.user_id
        member = User.find_by(id: goal_user_id)
        phone_number = member.phone_number.floor
        trigger_initial_message(goal_title, phone_number)
      # regular business
        redirect_to @goal 
        flash[:alert] = "Congrats,"
        flash[:notice] = "you've added your goal"
      else
        redirect_to "/goals/new" 
      end
  end

# send initial text message
  def trigger_initial_message(goal_title, phone_number)
    @content = "
      you're now tracking goal: #{goal_title}"
    send_message(phone_number, @content)
  end

# Set number of times a text will be sent through the allotted time
  def num_texts(minutes)
    if minutes == 0 
      data_pts = 0
    elsif minutes > 0 && minutes <= 60 # 1hr
      data_pts = 2
    elsif minutes > 60 && minutes <= 300 #5hr
      data_pts = 3
    elsif minutes > 300 && minutes <= 1440 #24hr
      data_pts = 4
    elsif minutes > 1440 && minutes <= 2880 #2 days
      data_pts = 6
    elsif minutes > 2880 && minutes <= 7200 #5 days
      data_pts = 12
    elsif minutes > 7200 && minutes <= 30240 #1 wk
      data_pts = 14
    elsif minutes > 30240 && minutes <= 40320 # 3 wks
      data_pts = 9
    elsif minutes > 40320 && minutes <= 241920 #1 mo
      data_pts = 25
    elsif minutes > 241920 && minutes <= 443520 #6 mo-11mo
      data_pts = 22
    end
    data_pts
  end 

# Calcuate minutes based on times provided
  def calculate_minutes_texts(time_allotted, time_allotted_units, goal_id)
    if(time_allotted_units = 1) # minutes
      minutes = time_allotted.to_i 
    elsif (time_allotted_units = 2) # hours
      minutes = time_allotted.to_i * 60 
    elsif (time_allotted_units = 3) # days
      minutes = time_allotted.to_i * 60 * 24 
    elsif (time_allotted_units = 4) # weeeks
      minutes = time_allotted.to_i * 60 * 24 * 7 
    elsif (time_allotted_units = 5) # months
      minutes = time_allotted.to_i * 60 * 24 * 7 * 4 
    elsif (time_allotted_units = 6) # years
      minutes = time_allotted.to_i * 60 * 24 * 7 * 4 * 12
    end
    # update minutes in each goal
    goal = Goal.where("id = #{goal_id}").first
    goal.update(time_allotted: minutes)
    # update total_data_pts for the number of texts to be sent
    data_pts = num_texts(minutes)
    goal.update(total_data_pts: data_pts)

    data_pts.times do |n|
      @data_pt = GoalDataPt.create(goal_id: goal_id, data_pt_num:n)
    end

  end



  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    id = @goal.user.id
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to "/users/#{id}", notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:goal_title, :time_allotted, :time_allotted_units, :goal_description, :goal_potential_met, :total_data_pts, :time_recommendation, :track_time, :speed_recommendation, :user_id)
    end

    def send_message(phone_number, content)
      @twilio_number = ENV['TWILIO_NUMBER']
      @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
      message = @client.account.messages.create(
          :from => @twilio_number,
          :to => phone_number,
          :body => content,
        )
      puts message.to
    end 

    # problem: need a fxn that only tells you congrats you've added a goal if you just did it within the create function
    # vs something she are seeing from the show fxn
    def just_created_goal(function)
      if function == create
        create
      elsif function == show
        show
      end
    end 

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
  <div class="container">
    <div class="row">
      <div class="headline col l12 offset-s2">
      <% if current_user %> 
        <p class="headline-introduction">let's</p>
        <p class="headline-content">add a new goal </p>
        <% end %> 


<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :goal_title %><br>
    <%= f.text_field :goal_title %>
  </div>
  <div class="field">
    <%= f.check_box :track_time, id: "track_time"%>
    <%= f.label :"track time", for:"track_time",  id: "track_time" %>
  </div>
    <div class="field hidden" id = "time_allotted">
      <%= f.label :"enter time (eg, 5 hours)" %><br>
      <%= select_tag :time_allotted_units, options_for_select([["minutes", 1], ["hours", 2], ["days", 3],["weeks", 4], ["months", 5], ["years", 6]]), :class => 'time_units' %>
      <%= f.number_field :time_allotted %>
    </div>
  <div class="field">
    <%= f.label :goal_description %><br>
    <%= f.text_area :goal_description %>
  </div>
  <div class="field"> 
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br>

      </div>
  </div>
</div>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Goals</h1>

<table>
  <thead>
    <tr>
      <th>Goal title</th>
      <th>Time allotted</th>
      <th>Goal description</th>
      <th>Goal potential met</th>
      <th>Total data pts</th>
      <th>Time recommendation</th>
      <th>Speed recommendation</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.goal_title %></td>
        <td><%= goal.time_allotted %></td>
        <td><%= goal.goal_description %></td>
        <td><%= goal.goal_potential_met %></td>
        <td><%= goal.total_data_pts %></td>
        <td><%= goal.time_recommendation %></td>
        <td><%= goal.speed_recommendation %></td>
        <td><%= goal.user %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<%= render 'form' %>

app/views/goals/show.html.erb
  <div class="container">
    <div class="row">
      <div class="headline col l12 offset-s2">
      <% if current_user %> 

          <%if flash[:alert] && flash[:notice]%>   
            <p class="headline-introduction"><%= flash[:alert] %> </p>
            <p class="headline-content"> <%= flash[:notice] %> </p>

          <%end %> 

        <% end %> 


<p id="notice"><%= notice %></p>

<p>
  <strong>Goal title:</strong>
  <%= @goal.goal_title %>
</p>

<p>
  <strong>Goal description:</strong>
  <%= @goal.goal_description %>
</p>

<%= link_to 'Destroy', @goal, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', goals_path %>


      </div>
    </div>
  </div>